import { createElement } from 'lwc';
import A07getSetChildPrimitive from 'c/a07getSetChildPrimitive';

describe('c-a07-get-set-child-primitive', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-a07-get-set-child-primitive', {
            is: A07getSetChildPrimitive
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});