import { createElement } from 'lwc';
import CreateAndEditAndDelete from 'c/createAndEditAndDelete';

describe('c-create-and-edit-and-delete', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-create-and-edit-and-delete', {
            is: CreateAndEditAndDelete
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});